matrix:
  include:
    - language: elixir
      elixir: '1.7'
      otp_release: '20.0'

      cache:
        directories:
          - assets/node_modules
          - assets/elm/elm-stuff
          - _build
          - deps

      services:
        - postgresql

      addons:
        postgresql: '9.6'

      before_install:
        - nvm install 12
        - (cd assets && npm install)

      before_script:
        - cp config/config.travis.exs config/config.exs
        - cp config/test.travis.exs config/test.exs
        - cp config/integration.travis.exs config/integration.exs
        - psql -c 'create database travis_ci_test;' -U postgres

      script:
        - mix test
        - MIX_ENV=integration mix integration.setup
        - cd assets
        - npm run deploy
        - npm test
        - npx prettier --check "{js,__tests__}/**/*.js" "*.js"
